### PR TITLE
Update master_preferences

### PR DESCRIPTION
**Pull request by Chrysostomus**
Use gtk-theme and system titlebars for better integration with desktops (mainly thinking about bspwm edition, which has chromium as the default browser)

### CODE REVIEW

**Comment by Chrysostomus** [comment]
@oberon2007 , does this make sense in other environments?

**Comment by Chrysostomus** [comment]
ping @oberon2007

**Comment by oberon2007** [comment]
To be honest I have no idea what this does ... ! 😆

**Comment by Chrysostomus** [comment]
It

- makes chromium follow the gtk3 theme by default instead of using the default chromium theme
- makes chromium use the titlebars and borders of the window manager instead of drawing its own. In case of i3 or bspwm, it means no window buttons and slightly bigger and cleaner window.

**Comment by Chrysostomus** [comment]
I can provide illustration maybe tomorrow

**Comment by codesardine** [comment]
I was about to send a patch for this @Chrysostomus 

https://forum.manjaro.org/t/set-chromium-default-theme-to-gtk/36608

**Comment by Chrysostomus** [comment]
Maybe I should make a separate package? It's been a month now without indication of if this is going somewhere, and this is the last issue to solve before releasing the next version of bspwm edition.

**Comment by codesardine** [comment]
Any thoughts on this?

**Comment by oberon2007** [comment]
I'm not all too happy to include this by default since it changes chromium's intended default behaviour.
Maybe a dedicated package for your editions would be a good thing?
@philmmanjaro ?

**Comment by Chrysostomus** [comment]
I already did it, manjaro-browser-settings-native. I also figured it was the most reasonable course of action. Btw, the pull request is dysfunctional, but I managed to get it working on the new package.

@codesardine I recommend you use that one instead.

**Comment by codesardine** [comment]
Ha ok, thanks :+1:

**Comment by philmmanjaro** [comment]
I'd say a NAK from me as well. Same as @oberon2007 already gave. The **native** package is the way to go here.

**Pull request closed without merging**
